In [2]:
## all imports
from IPython.display import HTML
import numpy as np
import urllib2
import bs4 #this is beautiful soup
import time
import operator
import socket
import cPickle
import re # regular expressions
import csv


from pandas import Series
import pandas as pd
from pandas import DataFrame

import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
sns.set_context("talk")
sns.set_style("white")

In [155]:
f_info = 'C:/projetos/cs109_marstival/linkedin_profile_info.csv'
f_pos_summary = 'C:/projetos/cs109_marstival/linkedin_profile_positions.csv'
f_pos_complete = 'C:/projetos/cs109_marstival/linkedin_profile_positions_details.csv'

dtypes=None
converters = None

columns=['rowid','profile_name', 'profile_name2','headline','location','link']
df_profiles = pd.read_csv(f_info, names=columns, delimiter=";",encoding="utf-8-sig")

columns=['rowid','position', 'period']

df_positions_alt = pd.read_csv(f_pos_summary, names=columns, delimiter=";",encoding="utf-8-sig",  converters=converters)

columns=['rowid','period', 'position','start','end','position_id']

def conv2(x):
    if (re.search("\A[0-9]{4}",x) is not None):
        x = 'January ' + x
    return x

converters = {'start':conv2,'end':conv2}

df_positions = pd.read_csv(f_pos_complete, names=columns, delimiter=";", encoding="utf-8-sig", converters=converters)


df_profiles['rowid']=df_profiles.rowid.astype(int)
df_positions['rowid']=df_positions.rowid.astype(int)
df_positions_alt['rowid']=df_positions_alt.rowid.astype(int)

df_positions['start'] = pd.to_datetime(df_positions.start, format='%B %Y', errors='coerce')
df_positions['end'] = pd.to_datetime(df_positions.end, format='%B %Y', errors='coerce')

In [154]:
def todate(date):
    print date
    if (date is None) or (str(date).lower() in ["nat", "nan", ""]):
        return None
    
    d = time.strptime(date,"%B %Y")
    return d

def fromdate(d):
    if (d is None) or (str(d).lower() in ["nat", "nan", ""]):
        return None
    s = time.strftime("%B %Y",d)
    return s

def date_isnull(d):
    if (d is None) or (str(d).lower() in ["nat", "nan", ""]):
        return True
    else:
        return False

In [149]:
#df_profiles = df_profiles[150:180]

Empty DataFrame
Columns: []
Index: []

In [157]:
#df_profiles.head()

num_of_profiles = len(df_profiles)
df_profiles['employee'] = num_of_profiles*False
df_profiles['transition_to'] = num_of_profiles* ""
df_profiles['transition_to_date'] = num_of_profiles * ""
df_profiles['transition_from'] = num_of_profiles* ""
df_profiles['transition_from_date'] = num_of_profiles * ""

df_profiles['transition_to_date'] = pd.to_datetime(df_profiles.transition_to_date, format='%B %Y', errors='coerce')
df_profiles['transition_from_date'] = pd.to_datetime(df_profiles.transition_from_date, format='%B %Y', errors='coerce')


for p in df_profiles.rowid:
    #execution info
    #print "\n begining for ", p
    df = df_positions[df_positions.rowid == p]
    #df = df.sort_values(by=['start'], ascending=False)
    
    df_current = df[(df.period == "currentPositionsDetails") & (df.position.str.contains("HSBC"))]
    employee = bool(len(df_current))
    
    pre_hsbc = post_hsbc = None
    for i, df_allps in df.iterrows():
        
        if (re.search("HSBC",df_allps.position.upper()) is not None):
            pre_hsbc = df_allps
            #print "\n post about to if ", df_allps.position.upper()
            if post_hsbc is not None:
                #print "\n post about to break ", df_allps.position.upper()
                break
                
        elif pre_hsbc is not None:
            post_hsbc = df_allps
            #print "\n pre about to break ", df_allps.position.upper()
            break
        else:
            post_hsbc = df_allps
            #print "\n pre about to coontin ", df_allps.position.upper()
            continue
    
    #print "\n emp ", employee
    #print "\n pre: ", pre_hsbc
    #print "\n post ", post_hsbc
    
    df_profiles.employee[df_profiles.rowid == p] = employee
    if (employee):
        if post_hsbc is not None:
            df_profiles.transition_from[df_profiles.rowid == p] = post_hsbc['position']
            df_profiles.transition_from_date[df_profiles.rowid == p] = post_hsbc['end']
        if pre_hsbc is not None:
            df_profiles.transition_to[df_profiles.rowid == p] = pre_hsbc['position']
            df_profiles.transition_to_date[df_profiles.rowid == p] = pre_hsbc['start']
    else:    
        if post_hsbc is not None:
            df_profiles.transition_to[df_profiles.rowid == p] = post_hsbc['position']
            df_profiles.transition_to_date[df_profiles.rowid == p] = post_hsbc['start']

        if pre_hsbc is not None:
            df_profiles.transition_from[df_profiles.rowid == p] = pre_hsbc['position']
            df_profiles.transition_from_date[df_profiles.rowid == p] = pre_hsbc['end']

    
#df_profiles.head()

C:\Users\marcelo\Anaconda2\lib\site-packages\ipykernel\__main__.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\marcelo\Anaconda2\lib\site-packages\ipykernel\__main__.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\marcelo\Anaconda2\lib\site-packages\ipykernel\__main__.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\marcelo\Anaconda2\lib\site-packages\ipykernel\__main__.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\marcelo\Anaconda2\lib\site-packages\ipykernel\__main__.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\marcelo\Anaconda2\lib\site-packages\ipykernel\__main__.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\marcelo\Anaconda2\lib\site-packages\ipykernel\__main__.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\marcelo\Anaconda2\lib\site-packages\ipykernel\__main__.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\marcelo\Anaconda2\lib\site-packages\ipykernel\__main__.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [159]:
df_profiles.head(100)
#df_positions[df_positions.rowid == 157].head()

,rowid,profile_name,profile_name2,headline,location,link,employee,transition_to,transition_to_date,transition_from,transition_from_date
0,1,Andrea Carvalho HSBC Bank Brasil S.A.,Andrea Carvalho HSBC Bank Brasil S.A.,RM WEALTH MANAGER HSBC Global Banking and Mar...,"São Paulo Area, Brazil",https://www.linkedin.com/in/andr%C3%A9a-carval...,1,HSBC Global Banking and Markets,1999-09-01,,NaT
1,2,Hsbc Bank,Hsbc Bank,banking at HSBC,United Kingdom,https://www.linkedin.com/in/hsbc-bank-1aa3bba5,1,HSBC,NaT,,NaT
2,3,Megan Steiner,Megan Steiner,"Vice President, Marketing at HSBC Commercial ...",Greater New York City Area,https://www.linkedin.com/in/megan-steiner-ba1a...,1,HSBC,2004-10-01,,NaT
3,4,HSBC Premier Steve Denning,HSBC Premier Steve Denning,Senior Premier Manager at HSBC,"London, United Kingdom",https://www.linkedin.com/in/hsbc-premier-steve...,1,HSBC,2008-05-01,,NaT
4,5,HSBC BANK LONDON,HSBC BANK LONDON,"The Director, Foreign Operations Department H...",United Kingdom,https://www.linkedin.com/in/hsbc-bank-london-3...,1,HSBC Commercial Banking,1976-10-01,,NaT
5,6,HSBC BANK PLC,HSBC BANK PLC,CHIEF FINANCIAL OFFICER AT HSBC BANK PLC,United Kingdom,https://www.linkedin.com/in/hsbc-bank-plc-a170...,1,HSBC HOLDINGS,1998-03-01,,NaT
6,7,Andrea Hsbc,Andrea Hsbc,Gerente Titular no HSBC Bank Brasil S/A - Ban...,"Uberaba, Minas Gerais, Brazil",https://www.linkedin.com/in/andrea-hsbc-0a961a71,1,HSBC Bank Brasil S/A - Banco Múltiplo,1999-05-01,Banco Sudameris,1999-05-01
7,8,Hsbc Mukhtar Chikte,Hsbc Mukhtar Chikte,Seeking new opportunities to enhance carrier,United Arab Emirates,https://www.linkedin.com/in/hsbc-mukhtar-chikt...,1,HSBC Retail Banking and Wealth Management,2004-04-01,,NaT
8,9,Katie Danby,Katie Danby,Chief Executive Officer,Monaco area,https://www.linkedin.com/in/katiedanby,1,HSBC,1996-08-01,,NaT
9,10,Drew Douglas,Drew Douglas,"Co-Head, HSBC Securities Services","London, United Kingdom",https://www.linkedin.com/in/drew-douglas-bb735aa,1,HSBC USA,2004-10-01,Bank of Bermuda Limited,2004-09-01
10,11,Hsbc Hsbc,Hsbc Hsbc,Premier Manager at HSBC,"Southampton, United Kingdom",https://www.linkedin.com/in/hsbc-hsbc-0068812a,1,HSBC,NaT,,NaT
11,13,Marcos V Ronconi (Hsbc),Marcos V Ronconi (Hsbc),gerente de serviços a clientes na HSBC,"Lages Area, Brazil",https://www.linkedin.com/in/marcos-v-ronconi-h...,1,HSBC,2003-03-01,,NaT
12,14,Frederick Hsbc,Frederick Hsbc,Manager Contact Centre and Digital Channels a...,Brunei Darussalam,https://www.linkedin.com/in/frederick-hsbc-839...,1,HSBC,2006-10-01,,NaT
13,15,Katen Mistry,Katen Mistry,HSBC Business Specialist supporting local bus...,"Rugby, Warwickshire, United Kingdom",https://www.linkedin.com/in/katenmistryhsbc,1,HSBC,1997-07-01,Wilkinson,1997-01-01
14,16,Hsbc Business Specialist,Hsbc Business Specialist,Business Specialist at HSBC,"London, United Kingdom",https://www.linkedin.com/in/hsbc-business-spec...,1,HSBC,NaT,,NaT
15,17,"Robert Langford, CFA","Robert Langford, CFA","Director, Global Banking and Markets at HSBC",Hong Kong,https://www.linkedin.com/in/robertlangfordcfa,1,HSBC Singapore,2004-01-01,,NaT
16,18,Hsbc In Uk Nesbitt,Hsbc In Uk Nesbitt,Bank Official at HSBC,"Derby, Derby, United Kingdom",https://www.linkedin.com/in/hsbc-in-uk-nesbitt...,1,HSBC,NaT,,NaT
17,19,Andy Johnston,Andy Johnston,Retired at HSBC,"Norfolk, Virginia Area",https://www.linkedin.com/in/ajvabch,1,HSBC,1985-01-01,,NaT
18,20,Ed Sterba,Ed Sterba,Chief Information Officer,"Baltimore, Maryland Area",https://www.linkedin.com/in/ed-sterba-64464031,0,Citibank - OneMain Financial,2012-04-01,HSBC,2011-05-01
19,22,Hsbc Plc,Hsbc Plc,director at banker,"Johannesburg Area, South Africa",https://www.linkedin.com/in/hsbc-plc-97857592,0,banker,NaT,,NaT
20,23,Warwick Long,Warwick Long,"Regional Head of Commercial Banking, Channel ...",Jersey,https://www.linkedin.com/in/warwick-long-6662a26b,1,HSBC,2008-03-01,,NaT
21,26,Andrew Metcalfe,Andrew Metcalfe,Senior International Relationship Manager at ...,United Kingdom,https://www.linkedin.com/in/andrew-metcalfe-44...,1,HSBC Bank UK,2008-03-01,,NaT
22,27,Ian Hexter,Ian Hexter,Change & Implementation Management at HSBC,"Sheffield, South Yorkshire, United Kingdom",https://www.linkedin.com/in/ianhexter,1,HSBC,1993-09-01,,NaT
23,29,James Barber,James Barber,"Head of Business Assurance, at HSBC",Jersey,https://www.linkedin.com/in/james-barber-92a24a5,1,HSBC,1999-11-01,Coca-Cola & Schweppes Beverages Ltd,1999-09-01
24,30,Aden Davies,Aden Davies,Financial services technologist and innovatio...,"Sheffield, United Kingdom",https://www.linkedin.com/in/adendavies,0,,NaT,HSBC,2003-10-01
25,31,HSBC insurance Careers,HSBC insurance Careers,Headhunter/Recruiter at HSBC Insurance (Singa...,Singapore,https://www.linkedin.com/in/hsbc-insurance-car...,1,HSBC Insurance (Singapore) Pte Ltd.,2007-01-01,,NaT
26,32,Alisson Augusto de Oliveira,Alisson Augusto de Oliveira,Estagiário no HSBC Brasil,"Curitiba, Paraná, Brazil",https://www.linkedin.com/in/alisson-augusto-de...,1,HSBC,2015-07-01,Editora Positivo,2015-07-01
27,33,hsbc bank,hsbc bank,SCAMMEDVICTIM521BENEFICIARIES at United Nations,Nigeria,https://www.linkedin.com/in/hsbc-bank-4a1255a6,0,United Nations,1998-09-01,,NaT
28,34,Ahmad Sabrey Hsbc Hsbc Bank,Ahmad Sabrey Hsbc Hsbc Bank,Premier Officer at HSBC,Egypt,https://www.linkedin.com/in/ahmad-sabrey-hsbc-...,1,HSBC,NaT,,NaT
29,35,HR HSBC Saudi,HR HSBC Saudi,Recruiter at HSBC,Saudi Arabia,https://www.linkedin.com/in/hr-hsbc-saudi-1b80...,1,HSBC,2006-06-01,,NaT
...,...,...,...,...,...,...,...,...,...,...,...
70,86,"Mr Darren Ng , HSBC Premier","Mr Darren Ng , HSBC Premier",Premier Service Manager at HSBC,Singapore,https://www.linkedin.com/in/mr-darren-ng-hsbc-...,1,HSBC,NaT,,NaT
71,87,HSBC Michael Sequriah,HSBC Michael Sequriah,Manager Change Delivery at HSBC,Malaysia,https://www.linkedin.com/in/hsbc-michael-sequr...,1,HSBC,NaT,,NaT
72,89,Mark Bowles,Mark Bowles,SVP - Capital Planning at HSBC,"New York, New York",https://www.linkedin.com/in/mark-bowles-7478064,1,HSBC,2004-11-01,PwC,2004-11-01
73,92,Belen Sepulveda/Hbmx/Hsbc,Belen Sepulveda/Hbmx/Hsbc,VP Global Markets Corporate Services HSBC Mex...,"Guadalajara Area, Mexico",https://www.linkedin.com/in/belen-sepulveda-hb...,1,HSBC Global Banking and Markets,2012-10-01,Banco Santander,2012-09-01
74,93,Leonor Pinto,Leonor Pinto,"Director, Debt Capital Markets, HSBC Bank plc","London, United Kingdom",https://www.linkedin.com/in/leonor-pinto-b5692...,1,HSBC Bank plc,2004-08-01,Banco Finantia,2004-06-01
75,94,Madhu Hsbc,Madhu Hsbc,Asistant Manager at HSBC,"Hyderabad Area, India",https://www.linkedin.com/in/madhu-hsbc-03857723,1,HSBC,2002-08-01,Eanudu Televison,2002-07-01
76,95,HSBC David,HSBC David,SVP Risk Management at HSBC,Taiwan,https://www.linkedin.com/in/hsbc-david-2793b1111,1,HSBC,NaT,,NaT
77,96,Jeanne Hsbc-Uk,Jeanne Hsbc-Uk,Associate at HSBC,"London, United Kingdom",https://www.linkedin.com/in/jeanne-hsbc-uk-4a0...,1,HSBC,NaT,,NaT
78,97,Vanchee Hsbc,Vanchee Hsbc,"Asst Mgr, Ext Agency Mgt at HSBC",Hong Kong,https://www.linkedin.com/in/vanchee-hsbc-3b04411a,1,HSBC,NaT,,NaT
79,98,Anurag Tripathi,Anurag Tripathi,Sr Vice President - Corporate Banking at HSBC,"Mumbai Area, India",https://www.linkedin.com/in/anuragtripathihsbc,1,HSBC,2006-05-01,Standard Chartered Bank,2006-05-01
80,99,Karin Cook,Karin Cook,"Group Director, Operations at Lloyds Banking ...","London, United Kingdom",https://www.linkedin.com/in/karin-cook-4851b15,0,Lloyds Banking Group,2013-03-01,HSBC Private Bank,2013-02-01
81,100,Steve Banner,Steve Banner,"Chief Executive Officer, Greece at HSBC",Greece,https://www.linkedin.com/in/steve-banner-2090041b,1,HSBC Bank Middle East Limited,2002-02-01,,NaT
82,102,Mark Watkinson,Mark Watkinson,Chief Executive Officer and Director at HSBC ...,Bermuda,https://www.linkedin.com/in/mark-watkinson-977...,1,HSBC United Arab Emirates,2001-09-01,,NaT
83,103,Patrick Carlos,Patrick Carlos,Senior Vice President & Head of Customer Expe...,"NCR - National Capital Region, Philippines",https://www.linkedin.com/in/patrickcarlos,1,HSBC,2012-08-01,Enderun Colleges,2015-05-01
84,104,Mohammed Hsbc,Mohammed Hsbc,Credit Manager at HSBC,United Arab Emirates,https://www.linkedin.com/in/mohammed-hsbc-6827...,1,HSBC,NaT,,NaT
85,105,Musharraf HSBC,Musharraf HSBC,WOE at HSBC,"Kolkata, West Bengal, India",https://www.linkedin.com/in/musharraf-hsbc-220...,1,HSBC,NaT,,NaT
86,106,Daniel Banque HSBC,Daniel Banque HSBC,DIRECTEUR ADJOINT chez HSBC,"Paris Area, France",https://www.linkedin.com/in/daniel-banque-hsbc...,1,HSBC,NaT,,NaT
87,107,"HSBC Investment Bank , Cotonou","HSBC Investment Bank , Cotonou","Investment Bank at HSBC Investment Bank , Cot...",Benin,https://www.linkedin.com/in/hsbc-investment-ba...,1,"HSBC Investment Bank , Cotonou",2002-07-01,,NaT
88,108,Timothy Katsoulis,Timothy Katsoulis,"General Counsel, HSBC Private Bank Americas a...",Greater New York City Area,https://www.linkedin.com/in/timothy-katsoulis-...,1,HSBC Private Bank,2008-01-01,Citigroup,2007-12-01
89,109,Apurba (Apu) Islam,Apurba (Apu) Islam,"Director, IT",Greater Chicago Area,https://www.linkedin.com/in/apurba-apu-islam-0...,0,Capital One,2013-03-01,HSBC,2013-03-01
90,111,HSBC-Andrian Prasety Prasetya,HSBC-Andrian Prasety Prasetya,Branch Manager HSBC Bandung at HSBC,Indonesia,https://www.linkedin.com/in/hsbc-andrian-prase...,1,HSBC,NaT,,NaT
91,112,Guy Lewis,Guy Lewis,Country Representative at HSBC Representative...,Nigeria,https://www.linkedin.com/in/guy-lewis-95bb859a,1,HSBC Bank Mauritius Ltd,2006-12-01,,NaT
92,113,sharon voss,sharon voss,Manager of Customer Service at HSBC,"Coventry, West Midlands, United Kingdom",https://www.linkedin.com/in/sharon-voss-14912363,1,HSBC,1988-01-01,,NaT
93,115,Gregory Nardiello,Gregory Nardiello,Global Head of Telecommunications at HSBC,Greater New York City Area,https://www.linkedin.com/in/gregory-nardiello-...,1,HSBC,1996-01-01,IBM Global Services,1996-05-01
94,117,Martin Tricaud,Martin Tricaud,President & CEO at HSBC Korea,Korea,https://www.linkedin.com/in/martin-tricaud-013...,1,HSBC Egypt,2000-08-01,,NaT
95,118,HSBC Philippe Khoury,HSBC Philippe Khoury,"MD - Global Co-Head, Strategic Energy Solutio...",Hong Kong,https://www.linkedin.com/in/hsbc-philippe-khou...,1,HSBC,2011-09-01,TOTAL,2011-09-01
96,119,Carolyn Taylor - HSBC,Carolyn Taylor - HSBC,Area Business Banking Mangager at HSBC,"Birmingham, United Kingdom",https://www.linkedin.com/in/carolyn-taylor-hsb...,1,HSBC,NaT,,NaT
97,120,Marilou Sullivan,Marilou Sullivan,SVP Service Delivery at HSBC,Greater Chicago Area,https://www.linkedin.com/in/marilou-sullivan-4...,1,HSBC Mortgage Services,1990-07-01,KPMG,1990-07-01
98,121,James Pomeroy,James Pomeroy,Global Economist at HSBC,"London, United Kingdom",https://www.linkedin.com/in/james-pomeroy-7b80...,1,HSBC,2012-07-01,Aberdeen Asset Management,2011-09-01
99,122,Zed Cama,Zed Cama,Group General Manager,Other,https://www.linkedin.com/in/zed-cama-04584817,1,hsbc holdings,2001-01-01,,NaT

In [162]:
df_profiles.to_csv('C:/projetos/cs109_marstival/linkedin_hsbc_transitions.csv', index=False,encoding="utf-8-sig")